site_name: Docathon
nav:
    - "Frontend": "frontend.md"
    - "API CRUD": "api_crud.md"
    - "Authentification": "authentification.md"
    - "DevOps": "devops.md"
theme:
    name: gitbook
plugins:
    - external-markdown
